-- 코드를 입력하세요
SELECT date_format(DATETIME,'%k') AS HOUR,  COUNT(*) as COUNT
FROM ANIMAL_OUTS
GROUP BY HOUR
HAVING CAST(HOUR AS UNSIGNED) >= 9 AND CAST(HOUR AS UNSIGNED) <= 19
ORDER BY CAST(HOUR AS UNSIGNED)